AWSTemplateFormatVersion: "2010-09-09"
Resources:
  euappRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: euroApp
      RepositoryDescription: This is a repository EUROPIPELINE.
      Code:
        BranchName: main
        S3: 
          Bucket: euroapps3
          Key: sampleApp.zip
  euPipeLine:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: arn:aws:iam::<aws-account-numer>:role/service-role/AWSCodePipelineServiceRole
      ArtifactStores:
        - ArtifactStore:
            Type: S3
            Location: codepipeline-eu-central-1-463785646796
          Region: eu-central-1
        - ArtifactStore:
            Type: S3
            Location: codepipeline-me-south-1-727534095386           
          Region: me-south-1 
      Stages:    
        - Name: SourceStage
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: "1"
              OutputArtifacts:
                - Name: SourceArtifact
              Configuration:
                RepositoryName: euroApp
                BranchName: main
                PollForSourceChanges: 'false'
              RunOrder: 1  
        - Name: CreateCodeDeployStackSet
          Actions:        
            - Name: CodeDeployStackSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormationStackSet
                Version: '1'
              RunOrder: 1
              Configuration:
                AdministrationRoleArn: arn:aws:iam::<aws-account-numer>:role/AWSCloudFormationStackSetAdministrationRole
                ExecutionRoleName: AWSCloudFormationStackSetExecutionRole
                DeploymentTargets: '<aws-account-numer>'
                FailureTolerancePercentage: '20'
                MaxConcurrentPercentage: '25'
                PermissionModel: SELF_MANAGED
                Regions: eu-central-1,me-south-1
                StackSetName: CemeaCodeDeployStackSet
                TemplatePath: 'SourceArtifact::WebAppCodeDeploy.yml'
              OutputArtifacts: []
              InputArtifacts:
                - Name: SourceArtifact
              Region: eu-central-1
              Namespace: DeployWebApp

        - Name: CreateStackSet
          Actions:        
            - Name: StackSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormationStackSet
                Version: '1'
              RunOrder: 1
              Configuration:
                AdministrationRoleArn: arn:aws:iam::<aws-account-numer>:role/AWSCloudFormationStackSetAdministrationRole
                ExecutionRoleName: AWSCloudFormationStackSetExecutionRole
                DeploymentTargets: '<aws-account-numer>'
                FailureTolerancePercentage: '20'
                MaxConcurrentPercentage: '25'
                PermissionModel: SELF_MANAGED
                Regions: eu-central-1,me-south-1
                StackSetName: CemeaStackSet
                TemplatePath: 'SourceArtifact::MyEC2Instance.yml'
              OutputArtifacts: []
              InputArtifacts:
                - Name: SourceArtifact
              Region: eu-central-1
              Namespace: DeployVariables
        - Name: DeployMeaAPP
          Actions:
            - Name: DeployEU
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CodeDeploy
                Version: '1'
              RunOrder: 1
              Configuration:
                ApplicationName: WebApp
                DeploymentGroupName: WebServerDGrp
              OutputArtifacts: []
              InputArtifacts:
                - Name: SourceArtifact
              Region: eu-central-1
              Namespace: DeployAppVars
            - Name: DeployME
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CodeDeploy
                Version: '1'
              RunOrder: 1
              Configuration:
                ApplicationName: WebApp
                DeploymentGroupName: WebServerDGrp
              OutputArtifacts: []
              InputArtifacts:
                - Name: SourceArtifact
              Region: me-south-1